config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get '/api-docs/v1/swagger.yaml', to: redirect('/swagger/v1/swagger.yml')

  # Defines the root path route ("/")
  devise_for :users
  root 'users#index'

  namespace :api, defaults: { format: :json} do
    namespace :v1 do
      resources :users, only: [:index, :create, :destroy] do
        resources :posts, only: [:index, :create, :destroy] do
          resources :comments, only: [:index, :create, :destroy]
          resources :likes, only: [:index, :create, :destroy]
        end
      end
    end
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:index, :new, :create, :destroy]
      resources :likes, only: [:create,]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_create :increment_posts_counter
  after_destroy :decrement_posts_counter

  def increment_posts_counter
    post.increment!(:comments_counter)
  end

  def decrement_posts_counter
    post.decrement!(:comments_counter)
  end

  private :increment_posts_counter, :decrement_posts_counter
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < ApplicationController
      load_and_authorize_resource

      def index
        @post = Post.find(params[:post_id])
        @user = User.find(params[:user_id])
        @comments = @post.comments
        render json: @comments
      end

      def create
        @comment = current_user.comments.new(comment_params)
        @comment.post_id = params[:post_id]
        if @comment.save
          render json: @comment, status: :created
        else
          render json: @comment.errors, status: :unprocessable_entity
        end
      end

      def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        if @comment.destroy
          head :no_content, status: :ok
        else
          render json: @comment.errors, status: :unprocessable_entity
        end
      end

      private

      def comment_params
        params.require(:comment).permit(:text)
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to user_post_comments_path(current_user, @comment.post_id)
    else
      render :create
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    if @comment.destroy
      flash[:success] = 'Comment deleted successfully'
      redirect_to user_post_comments_path(current_user, @comment.post_id)
    else
      flash.now[:error] = 'Error deleting comment'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/views/comments/form.html.erb
<%= form_with model: comment, url: user_posts_comments_path(@post.author, @post) do |form| %>
    <div>
        <%= form.label :text %>
        <%= form.text_area :text, size: "60x12" %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/comments/index.html.erb
<section class="indent">
    <h3>Comments</h3>
    <br>
    <button class="cancel-btn link">
        <%= link_to 'Back to post', user_post_path(@post.author, @post), style: 'color: black; text-decoration: none;' %>
    </button>
    <ul class="list">
        <% @post.comments.each do |comment| %>
            <li> <%= comment.author.name %>: <%= comment.text %> </li>
        <% end %>
    </ul>
</section>

app/views/comments/new.html.erb
<section class="indent">
    <%= form_with model: Comment, url: user_post_comments_path(@post.author, @post) do |form| %>
        <div class="form">
            <%= form.label :Comment %>
            <%= form.text_area :text, size: "50x8" %>
        </div>
        <div>
            <%= form.submit "save"%>
            <button class="cancel-btn link">
                <%= link_to 'Cancel', user_post_path(@post.author, @post), style: 'color: black; text-decoration: none;' %>
            </button>
        </div>
    <% end %>
</section>